// <auto-generated />
using System;
using Alderto.Bot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Alderto.Bot.Data.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20190703173058_Inintial")]
    partial class Inintial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Alderto.Bot.Data.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CurrencyCount");

                    b.Property<DateTime?>("CurrencyLastClaimed");

                    b.Property<ulong>("GuildId");

                    b.Property<ulong>("MemberId");

                    b.Property<Guid?>("RecruitedByMemberId");

                    b.HasKey("Id");

                    b.HasIndex("RecruitedByMemberId");

                    b.HasIndex("MemberId", "GuildId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Alderto.Bot.Data.Models.Member", b =>
                {
                    b.HasOne("Alderto.Bot.Data.Models.Member", "RecruitedByMember")
                        .WithMany("MembersRecruited")
                        .HasForeignKey("RecruitedByMemberId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
