// <auto-generated />
using System;
using Alderto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Alderto.Data.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    partial class SqliteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Alderto.Data.Models.Guild", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<char?>("Prefix");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Alderto.Data.Models.Member", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CurrencyCount");

                    b.Property<DateTime?>("CurrencyLastClaimed");

                    b.Property<ulong>("GuildId");

                    b.Property<ulong>("MemberId");

                    b.Property<uint?>("RecruitedByMemberId");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("RecruitedByMemberId");

                    b.HasIndex("MemberId", "GuildId")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Alderto.Data.Models.Member", b =>
                {
                    b.HasOne("Alderto.Data.Models.Guild", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Alderto.Data.Models.Member", "RecruitedByMember")
                        .WithMany("MembersRecruited")
                        .HasForeignKey("RecruitedByMemberId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
